# Scan-to-BIM Bootcamp Week 3

*This session will introduce point cloud processing algorithms such as downsampling and filtering, histograms, normal, curvature, line-fitting, plane-fitting, and Euclidean clustering.*

The assignment for this notebook is to use geometric operations to process a laser-scanned building point cloud.

# 1. Point Cloud Data Loading and Visualization

In [3]:
# Install the Open3D library
# This step is needed because Open3D is not a standard library included in Google Colab
!pip install open3d

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 408.6 MB 30 kB/s 
     |████████████████████████████████| 3.1 MB 38.4 MB/s 
     |████████████████████████████████| 1.1 MB 55.2 MB/s 
     |████████████████████████████████| 8.8 MB 41.2 MB/s 
     |████████████████████████████████| 54 kB 2.7 MB/s 
     |████████████████████████████████| 9.7 MB 33.2 MB/s 
     |████████████████████████████████| 344 kB 24.9 MB/s 
     |████████████████████████████████| 423 kB 25.8 MB/s 
     |████████████████████████████████| 1.6 MB 42.7 MB/s 
     |████████████████████████████████| 1.2 MB 67.9 MB/s 
     |████████████████████████████████| 80 kB 10.0 MB/s 
     |████████████████████████████████| 59 kB 7.8 MB/s 
     |████████████████████████████████| 55 kB 3.2 MB/s 
     |████████████████████████████████| 271 kB 51.4 MB/s 
     |████████████████████████████████| 133 kB 63.6 MB/s 
     |████████████████████████████████

In [1]:
# Mount a Google Drive folder so that the data files can be accessed
from google.colab import drive
from google.colab import files
import sys
drive.mount('/content/drive', force_remount=True)
%cd drive/MyDrive/Scan-to-BIM Bootcamp/Week 3/
sys.path.insert(0,'/content/drive/MyDrive/Scan-to-BIM Bootcamp/Week 3/')

Mounted at /content/drive
/content/drive/MyDrive/Scan-to-BIM Bootcamp/Week 3


In [4]:
# Import libraries and utility functions
import open3d as o3d
import numpy as np
from utils import draw_geometries

In [5]:
# Load a sample point cloud using the Open3D library
pcd_object = o3d.io.read_point_cloud("sample1.ply")
# Convert to a NumPy array for further processing
initial_pcd = np.hstack([pcd_object.points, pcd_object.colors]).astype(np.float32)
print("Point cloud dimensions are: ", initial_pcd.shape)
np.set_printoptions(precision=3, suppress=True)
print("Point cloud coordinates are:")
print(initial_pcd)

Point cloud dimensions are:  (76738, 6)
Point cloud coordinates are:
[[ 880.833 1149.219   97.833    0.514    0.533    0.557]
 [ 659.67   635.933  182.366    0.576    0.58     0.663]
 [ 659.567  635.883  182.494    0.055    0.067    0.141]
 ...
 [ 694.928  671.614  197.374    1.       1.       1.   ]
 [ 695.005  671.668  197.471    1.       1.       1.   ]
 [ 895.117  747.138  203.476    0.996    1.       1.   ]]


In [6]:
# Visualize the point cloud using a 3D web viewer
draw_geometries([pcd_object], show_axes=True)

Output hidden; open in https://colab.research.google.com to view.

# 2. Point cloud rotation

In [9]:
# Construct rotation matrix from a given angle

rotation_angle = -26.529492455418378 # degrees
theta = np.radians(rotation_angle)
R = np.array(((np.cos(theta), -np.sin(theta)), (np.sin(theta), np.cos(theta))))
print("Rotation matrix:")
print(R)

Rotation matrix:
[[ 0.895  0.447]
 [-0.447  0.895]]


In [10]:
# Apply rotation matrix to point cloud (x, y) coordinates

pcd_rotated = initial_pcd.copy()
pcd_rotated[:, :2] = R.dot(pcd_rotated[:, :2].T).T

In [11]:
# Visualize point cloud after rotation
pcd_object.points = o3d.utility.Vector3dVector(pcd_rotated[:, 0:3])
draw_geometries([pcd_object], show_axes=True)

Output hidden; open in https://colab.research.google.com to view.

# 3. Point cloud filtering

# 4. Euclidean clustering